export const SEARCH_FOCUSED = 'search_focused'
export const SEARCH_BLUR = 'search_blur'
export const INIT_HOTLIST_ACTION = 'init_hotlist_aciton'
export const MOUSE_IN = 'mouse_in'
export const MOUSE_OUT = 'mouse_out'
export const CHANGE_SWITCH = 'change_switch'
